# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PomodoroTimerUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PomodoroTimerUI(object):
    def setupUi(self, PomodoroTimerUI):
        PomodoroTimerUI.setObjectName("PomodoroTimerUI")
        PomodoroTimerUI.resize(400, 300)
        PomodoroTimerUI.setMinimumSize(QtCore.QSize(400, 300))
        PomodoroTimerUI.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/NewPath/Images/PomoFavicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PomodoroTimerUI.setWindowIcon(icon)
        self.LogoLabel = QtWidgets.QLabel(PomodoroTimerUI)
        self.LogoLabel.setGeometry(QtCore.QRect(100, 10, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LogoLabel.setFont(font)
        self.LogoLabel.setText("")
        self.LogoLabel.setPixmap(QtGui.QPixmap(":/NewPath/Images/PomoLogo.png"))
        self.LogoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LogoLabel.setObjectName("LogoLabel")
        self.WorkTimeLabel = QtWidgets.QLabel(PomodoroTimerUI)
        self.WorkTimeLabel.setGeometry(QtCore.QRect(80, 60, 241, 16))
        self.WorkTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.WorkTimeLabel.setObjectName("WorkTimeLabel")
        self.WorkTimeSpinner = QtWidgets.QSpinBox(PomodoroTimerUI)
        self.WorkTimeSpinner.setGeometry(QtCore.QRect(170, 90, 61, 22))
        self.WorkTimeSpinner.setMinimum(1)
        self.WorkTimeSpinner.setMaximum(120)
        self.WorkTimeSpinner.setObjectName("WorkTimeSpinner")
        self.BreakTimeLabel = QtWidgets.QLabel(PomodoroTimerUI)
        self.BreakTimeLabel.setGeometry(QtCore.QRect(80, 120, 241, 16))
        self.BreakTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.BreakTimeLabel.setObjectName("BreakTimeLabel")
        self.BreakTimeSpinner = QtWidgets.QSpinBox(PomodoroTimerUI)
        self.BreakTimeSpinner.setGeometry(QtCore.QRect(170, 150, 61, 22))
        self.BreakTimeSpinner.setMinimum(1)
        self.BreakTimeSpinner.setMaximum(120)
        self.BreakTimeSpinner.setObjectName("BreakTimeSpinner")
        self.TotalIntervalsLabel = QtWidgets.QLabel(PomodoroTimerUI)
        self.TotalIntervalsLabel.setGeometry(QtCore.QRect(80, 180, 241, 16))
        self.TotalIntervalsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TotalIntervalsLabel.setObjectName("TotalIntervalsLabel")
        self.TotalIntervalsSpinner = QtWidgets.QSpinBox(PomodoroTimerUI)
        self.TotalIntervalsSpinner.setGeometry(QtCore.QRect(170, 210, 61, 22))
        self.TotalIntervalsSpinner.setMinimum(1)
        self.TotalIntervalsSpinner.setMaximum(12)
        self.TotalIntervalsSpinner.setObjectName("TotalIntervalsSpinner")
        self.StartButton = QtWidgets.QPushButton(PomodoroTimerUI)
        self.StartButton.setGeometry(QtCore.QRect(150, 250, 101, 31))
        self.StartButton.setObjectName("StartButton")
        self.SoundCheckbox = QtWidgets.QCheckBox(PomodoroTimerUI)
        self.SoundCheckbox.setGeometry(QtCore.QRect(310, 280, 81, 17))
        self.SoundCheckbox.setObjectName("SoundCheckbox")
        self.TimerLabel = QtWidgets.QLabel(PomodoroTimerUI)
        self.TimerLabel.setGeometry(QtCore.QRect(10, 90, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.TimerLabel.setFont(font)
        self.TimerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimerLabel.setObjectName("TimerLabel")
        self.WorkOrBreakLabel = QtWidgets.QLabel(PomodoroTimerUI)
        self.WorkOrBreakLabel.setGeometry(QtCore.QRect(10, 170, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.WorkOrBreakLabel.setFont(font)
        self.WorkOrBreakLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.WorkOrBreakLabel.setObjectName("WorkOrBreakLabel")
        self.CompletedIntervalsLabel = QtWidgets.QLabel(PomodoroTimerUI)
        self.CompletedIntervalsLabel.setGeometry(QtCore.QRect(10, 200, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CompletedIntervalsLabel.setFont(font)
        self.CompletedIntervalsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CompletedIntervalsLabel.setObjectName("CompletedIntervalsLabel")
        self.StopButton = QtWidgets.QPushButton(PomodoroTimerUI)
        self.StopButton.setGeometry(QtCore.QRect(150, 250, 101, 31))
        self.StopButton.setObjectName("StopButton")
        self.CurrentStep = QtWidgets.QLCDNumber(PomodoroTimerUI)
        self.CurrentStep.setGeometry(QtCore.QRect(470, 270, 20, 23))
        self.CurrentStep.setObjectName("CurrentStep")
        self.BreakCounter = QtWidgets.QLCDNumber(PomodoroTimerUI)
        self.BreakCounter.setGeometry(QtCore.QRect(470, 240, 20, 23))
        self.BreakCounter.setObjectName("BreakCounter")
        self.WorkCounter = QtWidgets.QLCDNumber(PomodoroTimerUI)
        self.WorkCounter.setGeometry(QtCore.QRect(470, 210, 20, 23))
        self.WorkCounter.setObjectName("WorkCounter")

        self.retranslateUi(PomodoroTimerUI)
        QtCore.QMetaObject.connectSlotsByName(PomodoroTimerUI)

    def retranslateUi(self, PomodoroTimerUI):
        _translate = QtCore.QCoreApplication.translate
        PomodoroTimerUI.setWindowTitle(_translate("PomodoroTimerUI", "Form"))
        self.WorkTimeLabel.setText(_translate("PomodoroTimerUI", "How many minutes per work session?"))
        self.BreakTimeLabel.setText(_translate("PomodoroTimerUI", "How many minutes per break session?"))
        self.TotalIntervalsLabel.setText(_translate("PomodoroTimerUI", "How many total intervals?"))
        self.StartButton.setText(_translate("PomodoroTimerUI", "Start"))
        self.SoundCheckbox.setText(_translate("PomodoroTimerUI", "Alarm Sound"))
        self.TimerLabel.setText(_translate("PomodoroTimerUI", "TIMER"))
        self.WorkOrBreakLabel.setText(_translate("PomodoroTimerUI", "WorkOrBreak"))
        self.CompletedIntervalsLabel.setText(_translate("PomodoroTimerUI", "CompletedIntervals"))
        self.StopButton.setText(_translate("PomodoroTimerUI", "Stop"))
import PomoResources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PomodoroTimerUI = QtWidgets.QWidget()
    ui = Ui_PomodoroTimerUI()
    ui.setupUi(PomodoroTimerUI)
    PomodoroTimerUI.show()
    sys.exit(app.exec_())
